version: 2
jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run: apt-get update && apt-get install build-essential curl git openssh-client -y
      - run: curl -L https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz | tar xvz -- && mv ./hugo /usr/local/bin
      - add_ssh_keys:
          fingerprints:
            - "6e:66:1e:13:b2:d4:e6:a0:d2:21:75:48:52:3a:ee:51"
      - run: make deploy.ci

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
